name: OpenCloud
description: OpenCloud - Open source file management and collaboration platform
version: "1.0.0"
slug: opencloud
arch:
  - amd64
  - aarch64
url: https://github.com/axlFThn/hassio-addons
