name: OpenCloud
description: OpenCloud - Open source file management and collaboration platform
version: 1.0.0
slug: opencloud
image: ghcr.io/axlFThn/hassio-opencloud-{arch}-addon
arch:
  - amd64
  - arm64
startup: application
boot: auto
ports:
  9200/tcp: 9200
options:
  log_level: info
  initial_admin_password: changeme
  domain: http://localhost:9200
schema:
  log_level: list(debug|info|notice|warning|error|critical)?
  initial_admin_password: str
  domain: str
environment:
  LOG_LEVEL: info
privileged: []
volumes:
  data: {}
